### ISSUE TITLE
Color picker button doesn't work in Chrome

### ISSUE THREAD

**Issue by piotrowskiadam** [bitcraftlab/p5.gui#25]
Maybe I'm doing something wrong with p5.gui library in this example:

https://editor.p5js.org/Tingler/sketches/qOs-EMeM-

The button to pick a color doesn't seem to work in Chrome desktop version 84.0.4147.125 (Official Build) (64-bit).
Works in current Firefox Developer Edition and both mobile Firefox and mobile Chrome.

Same happens in Chrome for me even with the PacMan CodePen provided in documentation:
https://codepen.io/bitcraftlab/pen/GNKmGg

I asked on p5 discord but others report same issue.

**Comment by piotrowskiadam** [comment]
Strange I tested it on my work computer and it works in Chrome Version 76.0.3809.87 (Official Build) (64-bit).

**Comment by devalladares** [comment]
Chrome updated their color picker, which seemed to break the gui. Found an explanation here after a loooong search
https://support.google.com/chrome/thread/49563888?hl=en
However it'll only solve for your machine, not for other users if you share your program!
Hoping the author picks up on this, it's been like this for quite a while now

**Comment by dan-reznik** [comment]
just had the same issue -- color picker not working, hoping author will fix it as this is such an important element

**Comment by jaredleekatzman** [comment]
> Chrome updated their color picker, which seemed to break the gui. Found an explanation here after a loooong search
> https://support.google.com/chrome/thread/49563888?hl=en
> However it'll only solve for your machine, not for other users if you share your program!
> Hoping the author picks up on this, it's been like this for quite a while now

This worked for me on a Windows 10 with Chrome Version 87.0.4280.88 (Official Build) (64-bit)

**Comment by arlidge** [comment]
Colour Picker still broken with in Chrome Version 88.0.4324.192 (Official Build) (x86_64) - I hope we get a fix. Firefox 86.0 is still working with the colour picker.

**Comment by craftoid** [comment]
Hey everyone, this was an upstream bug in the quicksettings backend.
I added a quick fix after looking at this pull request: bit101/quicksettings#58

It's really just a small change in the css that gets injected by `quicksettings.js`.
Here's a screenshot of the demo in chrome:
<img width="400" alt="color-picker-800" src="https://user-images.githubusercontent.com/720669/109899449-2e614f80-7c96-11eb-8301-9cbaf1d04597.png">
